title: ShadeSec
description: Hacking/exploit dev/linux/etc
author: L E
github: https://github.com/le91688
about: VR/Exploit Dev/Web Hacking/ Programming
disqus_shortname: www-shadesec-com
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/espnshade"
    - icon: fa-stack-exchange
      link: "#"

share:
  twitter_username: espnshade
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Github
      url: https://github.com/le91688
    - text: XML Feed
      url: /feed.xml

url: "https://le91688.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
